name: Build, Zip, and Upload Release with Fine-Grained Token
on:
  push:
    tags:
      - 'v8.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish project
        run: dotnet publish ./Module1/Module1.csproj -c Release -o ./publish

      - name: Zip published output
        run: |
          cd publish
          zip -r ../Module1-${{ github.ref_name }}.zip .
          cd ..

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: Module1-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_FINE_PAT }}
